version: 2.1
jobs:
  
  insights_api_tests:
    docker:
      - image: circleci/node:latest
    steps:    
      - checkout
      - run: 
        name: Install newman
        command: sudo npm install -g newman
      - run:
        name: Run Insights Api tests with newman
        command: newman run postman/TestAPI.postman_collection.json -e postman/Local.postman_environment.json 