version: 2.1
orbs:
  node: corcleci/node@4.5.1 
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: postman/TestAPI.postman_collection.json          
          environment: postman/Local.postman_environment.json