version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:     
      - image: circleci/node    
    steps:
      - checkout
      - run:
          name: Get previous results
          command: |
            export ARTIFACT_LINK="https://circleci.com/api/v2/project/github/michael120288/QA_Challenge/latest/artifacts"
            curl $ARTIFACT_LINK -H "Circle-Token $CIRCLE_TOKEN" | grep -Eoq '(http|https)://[a-zA-Z0-9./?=_%:-]*' && wget $(curl $ARTIFACT_LINK -H "Circle-Token $CIRCLE_TOKEN" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_%:-]*') -O newman-previous.zip
            test -f newman-previous.zip && unzip newman-previous.zip -d newman-previous || echo "Archive not found"
            ls -la 
      - run:
          name: NPM Ignore
          command: sudo npm i -g npm ignore
      
      - run:
          name: Install Newman
          command: sudo npm install -g newman
          
      - run:
          name: Working Dir
          command: ls -la
      
      - run:
          name: API Testing 
          command: |
            newman run postman/TestAPI.postman_collection.json  --environment postman/Local.postman_environment.json
            ls -la
            test -d newman-previous && cp -r newman-previous/newman-report/history newman-results || echo "Previous report directory not found"
            npm run newman:ganerate-report
            zip -r newman-report.zip newman-report
      - run:
          when: on_fail
          name: Generate fail results
          command: |
            test -d newman-previous && cp -r newman-previous/newman-report/history newman-results || echo "Previous report directory not found"
            npm run newman:ganerate-report
            zip -r newman-report.zip newman-report
      - store_artifacts:
          path: newman-report.zip
  build2:
    working_directory: ~/repo
    docker:     
      - image: circleci/node:14.16.1-browsers  
    steps:
      - checkout      
      - run:
          name: Get previous results
          command: |
            export ARTIFACT_LINK="https://circleci.com/api/v2/project/github/michael120288/QA_Challenge/latest/artifacts"
            curl $ARTIFACT_LINK -H "Circle-Token $CIRCLE_TOKEN" | grep -Eoq '(http|https)://[a-zA-Z0-9./?=_%:-]*' && wget $(curl $ARTIFACT_LINK -H "Circle-Token $CIRCLE_TOKEN" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_%:-]*') -O allure-previous.zip
            test -f allure-previous.zip && unzip allure-previous.zip -d allure-previous || echo "Archive not found"
            ls -la     
      - run:
          name: Run tests
          command: |            
            npm install && npm test
            ls -la
            test -d allure-previous && cp -r allure-previous/allure-report/history allure-results || echo "Previous report directory not found"
            npm run report:generate
            zip -r allure-report.zip allure-report
      - run:
          when: on_fail
          name: Generate fail results
          command: |
            test -d allure-previous && cp -r allure-previous/allure-report/history allure-results || echo "Previous report directory not found"
            npm run report:generate
            zip -r allure-report.zip allure-report
      - store_artifacts:
          path: allure-report.zip
workflows:
  version: 2

  my_workflow:
    jobs:
      - build
      - build2
